# Generated by Django 5.2.1 on 2025-05-22 01:04

import django.db.models.deletion
import monografias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('autor', models.CharField(max_length=500)),
                ('orientador', models.CharField(max_length=500)),
                ('coorientador', models.CharField(blank=True, max_length=500, null=True)),
                ('resumo', models.TextField()),
                ('abstract', models.TextField()),
                ('palavras_chave', models.TextField()),
                ('data_defesa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=monografias.models.monografia_diretorio_upload)),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='monografias.monografia')),
            ],
        ),
    ]
