# Generated by Django 5.2.1 on 2025-05-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='nome_arquivo',
            field=models.CharField(default='nome-do-arquivo.pdf', max_length=500),
        ),
    ]
